name: nutrition
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # SDK extensions
  # flutter_localizations from sdk depends on meta 1.8.0
  meta: ^1.8.0
  # flutter_localizations from sdk depends on collection 1.16.0
  collection: ^1.16.0
  async: ^2.10.0

  # Stream
  stream_transform: ^2.1.0
  rxdart: ^0.27.7
  # System
  path_provider: ^2.0.12
  # flutter_localizations from sdk depends on path 1.8.2
  path: ^1.8.2
  platform_info: ^3.2.0
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  connectivity_plus: ^3.0.3

  # Data manipulation
  # stream_transform: ^2.1.0

  # BLoC
  bloc: ^8.1.1

  # Helper BLoC
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.1
  hydrated_bloc: ^9.1.0

  # Flutter integrations bloc
  flutter_bloc: ^8.1.2

  # Code generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Internationalization
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

  # Logging
  logger: ^1.1.0
  # sentry_flutter: ^6.18.1
  # stack_trace: ^1.11.0
  appmetrica_plugin: ^1.1.0

  # Persistance
  shared_preferences: ^2.0.17
  # sqflite_sqlcipher: ^2.1.1+1

  # HTTP
  dio: ^4.0.6
  dio_log: ^2.0.4

  # Navigation
  go_router: ^6.0.9

  # Native
  url_launcher: ^6.1.9
  share_plus: ^6.3.1

  # Helper for UI
  # flash: ^2.0.5
  lottie: ^2.2.0
  flutter_native_splash: ^2.2.17
  flutter_svg: ^2.0.1
  flex_color_scheme: ^6.1.2
  introduction_screen: ^3.1.6
  # syncfusion_flutter_pdfviewer: ^20.4.44
  # syncfusion_flutter_charts: ^20.4.44
  # syncfusion_flutter_calendar: ^20.4.44
  google_fonts: ^4.0.3
  flutter_typeahead: ^4.3.4
  # TEST
  device_preview: ^1.1.0
  feedback: ^2.5.0

  # Validation
  # mask_text_input_formatter: ^2.4.0
  crypto: ^3.0.2
  # firebase
  firebase_core: ^2.6.1
  firebase_crashlytics: ^3.0.14
  firebase_remote_config: ^3.0.12

  firebase_analytics: ^10.1.3
  firebase_performance: ^0.9.0+13

  # ******************************
  #  local packages
  # ******************************
  dadata:
    path: packages/dadata
  # turn_gen:
  #   git:
  #     url: https://github.com/a-dev-mobile/turn_gen.git
  #     ref: master

dev_dependencies:
  # Analyzer extensions
  dart_code_metrics: ^5.6.0
  very_good_analysis: ^4.0.0+1

  # Code generation
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  turn_gen: ^0.0.6

# Tests
#flutter_driver:
#  sdk: flutter
#integration_test:
#  sdk: flutter
#flutter_test:
#  sdk: flutter
# coverage: ^1.6.2
# test: ^1.22.1
#bloc_test: ^8.1.0
#mockito: ^5.1.0
#build_test: ^2.1.5

turn_gen:
  assets_output: "lib/gen/"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/lottie/
    - assets/image/
    - assets/icons/

  fonts:
    - family: app_icons
      fonts:
        - asset: assets/icons/app_icons.ttf
# flutter pub get && flutter pub run flutter_native_splash:create
# flutter_native_splash:
#   android: true
#   ios: true
#   web: true
#   desktop: true
#   color: "#ffffff"
#   image: assets/image/splash.png

